

	module.exports = {
          FilterBuilder                 : require('./src/FilterBuilder')
        , RelatedResourceController     : require('./src/RelatedResourceController')
        , RelatedService                : require('./src/RelatedService')
        , RelationalRequest             : require('./src/RelationalRequest')
        , RelationalResourceController  : require('./src/RelationalResourceController')
        , RelationalResponse            : require('./src/RelationalResponse')
        , RelationalSelection           : require('./src/RelationalSelection')
        , RelationalService             : require('./src/RelationalService')
        , RequestMiddleware             : require('./src/RequestMiddleware')
        , Request                       : require('./src/Request')
        , ResourceController            : require('./src/ResourceController')
        , Response                      : require('./src/Response')
        , SelectionBuilder              : require('./src/SelectionBuilder')
        , Service                       : require('./src/Service')
        , LegacyRequestTranslator       : require('./src/LegacyRequestTranslator')
        , ServiceManager                : require('./src/ServiceManager')
        , TestService                   : require('./src/TestService')
        , LegacyBridge                  : require('./src/LegacyBridge')
        , TestPermissionsService        : require('./src/TestPermissionsService')
        , Server                        : require('./src/Server')
        , WebsiteController             : require('./src/WebsiteController')
        , WebsiteService                : require('./src/WebsiteService')
        , APIGatewayParser              : require('./src/APIGatewayParser')
        , APIGatewayParserChild         : require('./src/APIGatewayParserChild')
        , APIGatewayService             : require('./src/APIGatewayService')
        , Hook                          : require('./src/Hook')
    }